version: "3.9"
services:
  webserver:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "./webServer/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - product_read
      - product_write
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  postgres:
    image: postgres:12.4 
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product_db
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  product_write:
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://root:root@postgres:5432/product_db"
      REDIS_URI: "redis://redis:6379"
      RPC_HOST: "tax"
    image: "python:3.8.1"
    ports: 
      - "3000:5000"
    volumes:
      - .:/app 
    working_dir: /app/product
    command: ./bootstrap.sh
    depends_on:
      - postgres
      - redis
      - tax
  product_read:
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://root:root@postgres:5432/product_db"
      REDIS_URI: "redis://redis:6379"
      RPC_HOST: "tax"
    image: "python:3.8.1"
    ports: 
      - "3001:5000"
    volumes:
      - .:/app 
    working_dir: /app/product
    command: ./bootstrap.sh
    depends_on:
      - postgres
      - redis
      - tax
  comments_write_async:
    environment:
      REDIS_URI: "redis://redis:6379"
    image: "python:3.8.1"
    ports: 
      - "3002:5000"
    volumes:
      - ./comments:/app 
    working_dir: /app
    command: ./bootstrap.sh
    depends_on:
      - redis
      - mongo
  comments_worker:
    environment:
      REDIS_URI: "redis://redis:6379"
      MONGO_URI: "mongodb://mongo:27017"
    image: "python:3.8.1"
    volumes:
      - ./comments:/app 
    working_dir: /app
    command: ./bootstrap_worker.sh
    depends_on:
      - redis
      - mongo
  tax:
    image: "python:3.8.1"
    ports: 
      - "50051:50051"
    volumes:
      - ./tax:/app 
    working_dir: /app
    command: ./bootstrap.sh
    depends_on:
      - postgres
      - redis
  
