version: "3.9"
services:
  webserver:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "./webServer/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - product_read
      - product_write
  postgres:
    image: postgres:12.4 
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product_db
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  product_write:
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://root:root@postgres:5432/product_db"
      REDIS_URI: "redis://redis:6379"
      RPC_HOST: "tax"
    image: "python:3.8.1"
    ports: 
      - "3000:5000"
    volumes:
      - .:/app 
    working_dir: /app/product
    command: ./bootstrap.sh
    depends_on:
      - postgres
      - redis
      - tax
  product_read:
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql://root:root@postgres:5432/product_db"
      REDIS_URI: "redis://redis:6379"
      RPC_HOST: "tax"
    image: "python:3.8.1"
    ports: 
      - "3001:5000"
    volumes:
      - .:/app 
    working_dir: /app/product
    command: ./bootstrap.sh
    depends_on:
      - postgres
      - redis
      - tax
  tax:
    image: "python:3.8.1"
    ports: 
      - "50051:50051"
    volumes:
      - ./tax:/app 
    working_dir: /app
    command: ./bootstrap.sh
    depends_on:
      - postgres
      - redis
  
