# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tax_pb2 as tax__pb2


class TaxStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCalculatedPrice = channel.unary_unary(
                '/tax.Tax/GetCalculatedPrice',
                request_serializer=tax__pb2.Product.SerializeToString,
                response_deserializer=tax__pb2.CalculatedTax.FromString,
                )


class TaxServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCalculatedPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCalculatedPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCalculatedPrice,
                    request_deserializer=tax__pb2.Product.FromString,
                    response_serializer=tax__pb2.CalculatedTax.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tax.Tax', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tax(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCalculatedPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/tax.Tax/GetCalculatedPrice',
            tax__pb2.Product.SerializeToString,
            tax__pb2.CalculatedTax.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
